# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinkBluCon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LinkBluCon
platform :ios, '9.0'
use_frameworks!
pod 'BlueCapKit', '~> 0.4'
end

